# SonarCloud automatic analysis settings (read from the repository root).
#
# The stylesheets under app/ are Tailwind 4 source, not plain CSS: they use
# @theme, @utility with nested "&" rules, @custom-variant and mid-file @import
# that Tailwind inlines at build time. Sonar's CSS analyzer parses them as
# plain CSS and reports "missing scoping root", "invalid position for
# declaration" and "invalid position for @import" on every such block, which
# failed the reliability gate on PR 105 with 16 false positives. Biome lints
# these files and scripts/check-ui-tokens.mjs guards their conventions, so
# they are excluded from Sonar's CSS rules here.
sonar.exclusions=app/*.css
