"use client";

import { ImageOff } from "lucide-react";
import { useState } from "react";

/**
 * Static-export image component for catalog artwork.
 *
 * Emits a native `<picture>` with AVIF -> WebP -> JPG sources, each carrying
 * a 4-width srcset (400 / 800 / 1200 / 1600). The browser picks the smallest
 * variant whose width covers the rendered CSS width times its devicePixelRatio.
 *
 * Variants live at `public/_opt/artworks/<slug>-<width>.<ext>`, generated by
 * `pnpm run optimize:images` (runs as part of `pnpm build`). The original
 * full-resolution JPG stays at `public/artworks/<slug>.jpg` as the JPG
 * fallback for browsers without AVIF/WebP support, and as the master copy
 * future re-encodes derive from.
 *
 * On a 404 (typo in `data/artworks.json`, missing variant in `_opt/`) the
 * `<img>`'s `onError` fires and we render a soft placeholder so the broken-
 * image icon never reaches a visitor.
 *
 * Why not next/image? `output: "export"` ships to GH Pages which has no
 * Node runtime. `images.unoptimized: true` would emit the raw 2-3 MB master
 * to every visitor. Hand-rolling `<picture>` gives us responsive variants
 * with zero JS at runtime.
 */
interface ArtImageProps {
	/** Path to the master JPG, e.g. "/artworks/radha-krishna.jpg". */
	src: string;
	alt: string;
	className?: string;
	/** Marks the image LCP-critical: eager fetch, high priority. */
	priority?: boolean;
	/**
	 * CSS layout sizes hint for the browser's variant picker. Mirrors the
	 * grid widths of the consumer (e.g. "(min-width: 1024px) 33vw, 50vw").
	 */
	sizes: string;
}

const WIDTHS = [400, 800, 1200, 1600] as const;

function deriveSlug(src: string): string {
	// "/artworks/radha-krishna.jpg" -> "radha-krishna"
	const file = src.split("/").pop() ?? "";
	return file.replace(/\.[^.]+$/, "");
}

function buildSrcset(slug: string, ext: "avif" | "webp"): string {
	return WIDTHS.map((w) => `/_opt/artworks/${slug}-${w}.${ext} ${w}w`).join(", ");
}

// JPG fallback path under _opt/ -- mozjpeg-encoded at master width, ~50%
// smaller than the baseline-encoded master in /artworks/. The master stays
// in the repo as the single source of truth; only this fallback ships.
function jpegFallback(slug: string): string {
	return `/_opt/artworks/${slug}.jpg`;
}

export function ArtImage({ src, alt, className, priority = false, sizes }: ArtImageProps) {
	const [failed, setFailed] = useState(false);

	if (failed) {
		return (
			<div
				role="img"
				aria-label={alt}
				className="absolute inset-0 grid place-items-center bg-bg-soft text-muted"
			>
				<ImageOff size={28} aria-hidden="true" />
			</div>
		);
	}

	const slug = deriveSlug(src);

	return (
		<picture>
			<source type="image/avif" srcSet={buildSrcset(slug, "avif")} sizes={sizes} />
			<source type="image/webp" srcSet={buildSrcset(slug, "webp")} sizes={sizes} />
			<img
				src={jpegFallback(slug)}
				alt={alt}
				loading={priority ? "eager" : "lazy"}
				decoding={priority ? "sync" : "async"}
				fetchPriority={priority ? "high" : "auto"}
				className={className ?? "absolute inset-0 h-full w-full object-cover"}
				onError={() => setFailed(true)}
			/>
		</picture>
	);
}
