/**
 * One-shot: upload artwork image variants to Cloudflare R2.
 *
 * Run after the variants exist locally (they're generated by
 * `pnpm run optimize:images`, part of `pnpm build`) and R2 env is set:
 *   pnpm run optimize:images   # ensure public/_opt/artworks/ is fresh
 *   pnpm db:images             # this script
 *
 * Uploads every file in public/_opt/artworks/ to R2 under the `artworks/`
 * prefix, preserving filenames. The gallery's ARTWORK_IMAGE_BASE then resolves
 * to `<R2_PUBLIC_BASE_URL>/artworks/<slug>-<width>.<ext>` -- a 1:1 path match
 * with the local `/_opt/artworks/` layout, so no component code changes.
 *
 * Idempotent: re-running re-uploads (overwrites) the same keys. Safe.
 */
import { readdir, readFile } from "node:fs/promises";
import { extname, join } from "node:path";
import { uploadObject } from "../lib/storage/r2";

const OPT_DIR = join(process.cwd(), "public", "_opt", "artworks");

const CONTENT_TYPE: Record<string, string> = {
	".avif": "image/avif",
	".webp": "image/webp",
	".jpg": "image/jpeg",
	".jpeg": "image/jpeg",
	".png": "image/png",
};

async function main() {
	let files: string[];
	try {
		files = await readdir(OPT_DIR);
	} catch {
		console.error(`No ${OPT_DIR}. Run \`pnpm run optimize:images\` first.`);
		process.exit(1);
	}

	const images = files.filter((f) => extname(f).toLowerCase() in CONTENT_TYPE);
	if (images.length === 0) {
		console.error("No image variants found to upload.");
		process.exit(1);
	}

	console.log(`Uploading ${images.length} variants to R2 under artworks/ ...`);
	let done = 0;
	// Bounded concurrency so we don't open 273 sockets at once.
	const POOL = 12;
	const queue = [...images];
	async function worker() {
		while (queue.length) {
			const file = queue.shift();
			if (!file) break;
			const buf = await readFile(join(OPT_DIR, file));
			const type = CONTENT_TYPE[extname(file).toLowerCase()];
			await uploadObject(`artworks/${file}`, buf, type);
			done += 1;
			if (done % 25 === 0 || done === images.length) {
				console.log(`  ${done}/${images.length}`);
			}
		}
	}
	await Promise.all(Array.from({ length: POOL }, worker));
	console.log(`Done. ${done} files uploaded to R2 (artworks/).`);
}

main().catch((err) => {
	console.error("R2 image migration failed:", err);
	process.exit(1);
});
